import type { CalculatorInputs } from "@/lib/calculator/types";

export const DEFAULT_CURRENT_AGE = 30;
export const DEFAULT_RETIREMENT_AGE = 65;
export const DEFAULT_LIFE_EXPECTANCY = 90;
export const DEFAULT_CURRENT_BALANCE = 25_000;
export const DEFAULT_ANNUAL_SALARY = 90_000;
export const DEFAULT_CONTRIBUTION_PERCENT = 10;
export const DEFAULT_EMPLOYER_MATCH_PERCENT = 4;
export const DEFAULT_ANNUAL_SALARY_GROWTH_PERCENT = 3;
export const DEFAULT_ANNUAL_RETURN_PERCENT = 7;
export const DEFAULT_INFLATION_PERCENT = 2.5;
export const DEFAULT_WITHDRAWAL_RATE_PERCENT = 4;
export const TARGET_RETIREMENT_SPENDING_SALARY_MULTIPLIER = 0.8;
export const DEFAULT_TARGET_RETIREMENT_SPENDING = Math.round(
  DEFAULT_ANNUAL_SALARY * TARGET_RETIREMENT_SPENDING_SALARY_MULTIPLIER
);
export const EMPLOYEE_CONTRIBUTION_LIMIT = 23_000;
export const CATCH_UP_CONTRIBUTION_LIMIT = 7_500;
export const DEFAULT_ANNUAL_EMPLOYEE_CONTRIBUTION_LIMIT = EMPLOYEE_CONTRIBUTION_LIMIT;
export const DEFAULT_WINDFALL_AGE = 50;
export const DEFAULT_WINDFALL_AMOUNT = 0;

export const defaultCalculatorInputs: CalculatorInputs = {
  currentAge: DEFAULT_CURRENT_AGE,
  retirementAge: DEFAULT_RETIREMENT_AGE,
  lifeExpectancy: DEFAULT_LIFE_EXPECTANCY,
  currentBalance: DEFAULT_CURRENT_BALANCE,
  annualSalary: DEFAULT_ANNUAL_SALARY,
  contributionPercent: DEFAULT_CONTRIBUTION_PERCENT,
  employerMatchPercent: DEFAULT_EMPLOYER_MATCH_PERCENT,
  annualSalaryGrowthPercent: DEFAULT_ANNUAL_SALARY_GROWTH_PERCENT,
  annualReturnPercent: DEFAULT_ANNUAL_RETURN_PERCENT,
  inflationPercent: DEFAULT_INFLATION_PERCENT,
  withdrawalRatePercent: DEFAULT_WITHDRAWAL_RATE_PERCENT,
  targetRetirementSpending: DEFAULT_TARGET_RETIREMENT_SPENDING,
  windfallAge: DEFAULT_WINDFALL_AGE,
  windfallAmount: DEFAULT_WINDFALL_AMOUNT,
};
