import type { CalculatorInputs } from "@/lib/calculator/types";

export const DEFAULT_CURRENT_AGE = 30;
export const DEFAULT_RETIREMENT_AGE = 65;
export const DEFAULT_LIFE_EXPECTANCY = 90;
export const DEFAULT_CURRENT_BALANCE = 25_000;
export const DEFAULT_ANNUAL_SALARY = 90_000;
export const DEFAULT_CONTRIBUTION_PERCENT = 10;
export const DEFAULT_ROTH_CONTRIBUTION_PERCENT = 0;
export const DEFAULT_EMPLOYER_MATCH_PERCENT = 4;
export const DEFAULT_ANNUAL_SALARY_GROWTH_PERCENT = 3;
export const DEFAULT_ANNUAL_RETURN_PERCENT = 7;
export const DEFAULT_INFLATION_PERCENT = 2.5;
export const TARGET_RETIREMENT_SPENDING_SALARY_MULTIPLIER = 0.8;
export const DEFAULT_TARGET_RETIREMENT_SPENDING = Math.round(
  DEFAULT_ANNUAL_SALARY * TARGET_RETIREMENT_SPENDING_SALARY_MULTIPLIER
);
export const DEFAULT_RETIREMENT_SPENDING_INFLATION_ADJUSTED = true;
export const DEFAULT_AGE_BASED_SPENDING_ENABLED = false;
export const DEFAULT_EARLY_RETIREMENT_SPENDING_PERCENT = 100;
export const DEFAULT_MID_RETIREMENT_SPENDING_PERCENT = 90;
export const DEFAULT_LATE_RETIREMENT_SPENDING_PERCENT = 80;
export const EMPLOYEE_CONTRIBUTION_LIMIT = 24_500;
export const CATCH_UP_CONTRIBUTION_LIMIT = 8_000;
export const SUPER_CATCH_UP_CONTRIBUTION_LIMIT = 11_250;
export const TOTAL_CONTRIBUTION_LIMIT = 72_000;
export const COMPENSATION_LIMIT = 360_000;
export const DEFAULT_ANNUAL_EMPLOYEE_CONTRIBUTION_LIMIT = EMPLOYEE_CONTRIBUTION_LIMIT;
export const DEFAULT_WINDFALL_AGE = 50;
export const DEFAULT_WINDFALL_AMOUNT = 0;

export const defaultCalculatorInputs: CalculatorInputs = {
  currentAge: DEFAULT_CURRENT_AGE,
  retirementAge: DEFAULT_RETIREMENT_AGE,
  lifeExpectancy: DEFAULT_LIFE_EXPECTANCY,
  currentBalance: DEFAULT_CURRENT_BALANCE,
  annualSalary: DEFAULT_ANNUAL_SALARY,
  contributionPercent: DEFAULT_CONTRIBUTION_PERCENT,
  rothContributionPercent: DEFAULT_ROTH_CONTRIBUTION_PERCENT,
  employerMatchPercent: DEFAULT_EMPLOYER_MATCH_PERCENT,
  annualSalaryGrowthPercent: DEFAULT_ANNUAL_SALARY_GROWTH_PERCENT,
  annualReturnPercent: DEFAULT_ANNUAL_RETURN_PERCENT,
  inflationPercent: DEFAULT_INFLATION_PERCENT,
  targetRetirementSpending: DEFAULT_TARGET_RETIREMENT_SPENDING,
  retirementSpendingInflationAdjusted: DEFAULT_RETIREMENT_SPENDING_INFLATION_ADJUSTED,
  ageBasedSpendingEnabled: DEFAULT_AGE_BASED_SPENDING_ENABLED,
  earlyRetirementSpendingPercent: DEFAULT_EARLY_RETIREMENT_SPENDING_PERCENT,
  midRetirementSpendingPercent: DEFAULT_MID_RETIREMENT_SPENDING_PERCENT,
  lateRetirementSpendingPercent: DEFAULT_LATE_RETIREMENT_SPENDING_PERCENT,
  windfallAge: DEFAULT_WINDFALL_AGE,
  windfallAmount: DEFAULT_WINDFALL_AMOUNT,
};
