export const theme = {
  colors: {
    text: "#111111",
    textSecondary: "#555555",
    background: "#F7F7F7",
    surface: "#FFFFFF",
    surfaceMuted: "#FAFAFA",
    border: "#EAEAEA",
    borderStrong: "#D4D4D4",
    accent: "#2563EB",
    accentHover: "#1D4ED8",
    mutedText: "#6B7280",
    mutedTextStrong: "#4B5563",
    focusRing: "rgba(15, 23, 42, 0.14)",
    infoSurface: "#FFFBEB",
    infoBorder: "#FDE68A",
    infoText: "#92400E",
    successSurface: "#F7FCF8",
    successBorder: "#D8E8DD",
    successText: "#355245",
    warningSurface: "#FFFDF8",
    warningBorder: "#EADFCF",
    warningText: "#664F2D",
    dangerSurface: "#FFFAFB",
    dangerBorder: "#EAD8D8",
    dangerText: "#6A4343",
    elevatedBorder: "#DBE4EF",
    elevatedBorderHover: "#D3DDE9",
    elevatedGradient: "linear-gradient(180deg, #FFFFFF 0%, #FAFCFF 100%)",
    chartGrid: "#EAEFF5",
    chartCursor: "#CFD8E3",
    chartMain: "#1F2937",
    chartInflation: "#6F7E96",
    chartTarget: "#0B7285",
    chartEvent: "#334155",
    chartWindfall: "#0F766E",
    chartDepletion: "#8A5858",
  },
  radii: {
    md: "14px",
    lg: "20px",
    xl: "24px",
    pill: "999px",
  },
  layout: {
    maxWidth: "1100px",
    sectionYMobile: "56px",
    sectionYTablet: "64px",
    sectionYDesktop: "80px",
    containerXMobile: "20px",
    containerXTablet: "32px",
    containerXDesktop: "40px",
  },
  breakpoints: {
    sm: "640px",
    md: "768px",
    lg: "1024px",
  },
} as const;

export type AppTheme = typeof theme;
